services:
  webserver:
    image: ghcr.io/htl-leonding/webserver:latest
    build:
      context: ../webserver
      dockerfile: ./src/main/docker/Dockerfile
    restart: always
    environment:
      POSTGRES_HOST: postgres
    healthcheck:
      test: curl -fsS http://localhost:8080
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
